### ISSUE TITLE
Example test

### ISSUE THREAD

**Issue by Alice-yyt** [benradford/replication_arxiv_1803_10769#1]
Hi, could you give me an example test dataset to learn this project? 😊 Thank you!

**Comment by benradford** [comment]
Hi Alice, 

Unfortunately, I am not allowed to distribute this dataset. However, you may find the dataset here: [www.unb.ca/cic/datasets/ids.html](https://www.unb.ca/cic/datasets/ids.html)

You'll want the one at the bottom of the page called UNB ISCX IDS 2012. You may need to request access from the Canadian Institute for Cybersecurity (CIC). 

Good luck!
Ben
